// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package class diagram;



/************************************************************/
/**
 * 
 */
public class accounts {
				/**
				 * 
				 */
				public int due_date;
				/**
				 * 
				 */
				public boolean status;
	/**
	 * 
	 * @param student_id 
	 */
	public void generate_rent(undef student_id) {
	}
}
