// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package class diagram;



/************************************************************/
/**
 * 
 */
public class complaints {
				/**
				 * 
				 */
				public int complaint_ticket;
				/**
				 * 
				 */
				public String comment;
				/**
				 * 
				 */
				public boolean complaint_status;
	/**
	 * 
	 * @param student_id 
	 * @param facility_id 
	 */
	public void submit_complain(undef student_id, undef facility_id) {
	}
	/**
	 * 
	 * @param complaint_ticket 
	 */
	public void check_complain_status(undef complaint_ticket) {
	}
}
