// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package class diagram;



/************************************************************/
/**
 * 
 */
public class facilities {
				/**
				 * 
				 */
				public int facility_id;
				/**
				 * 
				 */
				public String facility_name;
				/**
				 * 
				 */
				public int[] facility_rent;
				/**
				 * 
				 */
				public complaints[] complaints;
}
