// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package class diagram;



/************************************************************/
/**
 * 
 */
public class hostel_details {
				/**
				 * 
				 */
				public int hostel_id;
				/**
				 * 
				 */
				public String hostel_name;
				/**
				 * 
				 */
				public String hostel_address;
				/**
				 * 
				 */
				public int[] total_rooms;
				/**
				 * 
				 */
				public int base_rent;
				/**
				 * 
				 */
				private String password;
				/**
				 * 
				 */
				public facilities[] facilities;
				/**
				 * 
				 */
				public rooms[] rooms;
				/**
				 * 
				 */
				public accounts[] accounts;
	/**
	 * 
	 */
	public void signup() {
	}
	/**
	 * 
	 * @param hostel_name 
	 * @param password 
	 */
	public void login(undef hostel_name, undef password) {
	}
	/**
	 * 
	 * @param student_id 
	 */
	public void add_student(undef student_id) {
	}
	/**
	 * 
	 * @param facility_id 
	 */
	public void manage_facility(undef facility_id) {
	}
}
