// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package class diagram;



/************************************************************/
/**
 * 
 */
public class student_details {
				/**
				 * 
				 */
				public String first_name;
				/**
				 * 
				 */
				public String last_name;
				/**
				 * 
				 */
				public int phone_number;
				/**
				 * 
				 */
				public int CNIC;
				/**
				 * 
				 */
				public String guardian_name;
				/**
				 * 
				 */
				public String address;
				/**
				 * 
				 */
				public int join_date;
				/**
				 * 
				 */
				private String password;
				/**
				 * 
				 */
				public int student_id;
				/**
				 * 
				 */
				public hostel_details[] hostel_details;
				/**
				 * 
				 */
				public facilities[] facilities;
				/**
				 * 
				 */
				public complaints[] complaints;
				/**
				 * 
				 */
				public rooms rooms;
				/**
				 * 
				 */
				public accounts accounts;
	/**
	 * 
	 */
	public void signuo() {
	}
	/**
	 * 
	 * @param first_name 
	 * @param last_name 
	 * @param password 
	 */
	public void login(undef first_name, undef last_name, undef password) {
	}
	/**
	 * 
	 */
	public void check_status() {
	}
	/**
	 * 
	 * @param facility_id 
	 */
	public void ask_for_facility(undef facility_id) {
	}
	/**
	 * 
	 * @param facility_id 
	 */
	public void complaint_abbt_facility(undef facility_id) {
	}
	/**
	 * 
	 * @param facility_id 
	 */
	public void withdraw_facility(undef facility_id) {
	}
	/**
	 * 
	 */
	public void check_status() {
	}
}
